labels:
  bug:
    keywords:
      - bug
      - weird
    caseSensitive: false
  feature-request:
    keywords:
      - feature
      - improvement
      - idea
      - suggestion
      - request
    caseSensitive: false
