# https://github.com/marketplace/actions/github-issue-labeler

- bug:
    - bug
    - weird
    - caseSensitive: false
- feature\\-request:
    - feature\\
    - improvement
    - idea
    - suggestion
    - request
    - caseSensitive: false
