---
name: calendarr
# ╔══════════════════════════════════════╗
# ║               SERVICES               ║
# ╚══════════════════════════════════════╝
services:
 calendarr:
    image: jordyjordyjordy/calendarr:latest
    # build: .
    restart: "no"
    container_name: calendarr
    environment:
      USE_DISCORD: "false"
      USE_SLACK: "true"
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      # type must be "tv" or "movie"
      CALENDAR_URLS: >
        [{
          "url":"${ICS_URL_SONARR_1}",
          "type":"tv"
        },
        {
          "url":"${ICS_URL_RADARR_1}",
          "type":"movie"
        },
        {
          "url":"${ICS_URL_SONARR_2}",
          "type":"tv"
        }]
      CUSTOM_HEADER: TV Guide - Shows and Movies airing this week
      SHOW_DATE_RANGE: true
      START_WEEK_ON_MONDAY: true
      RUN_ON_STARTUP: true
      CRON_SCHEDULE: 0 9 * * 1 # Run every Monday at 9 AM
    volumes:
      - ./calendarr/logs:/app/logs:rw
