---
name: '🐛 Bug Report'
description: Create a report to help us improve
title: "\U0001F41B :"
labels: [bug]
# assignees: ''
projects: ["jordanlambrecht/calendarr/3"]
---

body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What happened? Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: checkboxes
    id: platforms-impacted
    attributes:
      label: Platform Impacted:
      options:
        - label: Slack
        - label: Discord
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. Enable debug in the compose file before copy/pasting log files. Please be sure to redact any sensitive information. This will be automatically formatted into code, so no need for backticks.
      render: shell
