name: Add feature requests to project

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  add-to-project:
    name: Add feature request to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: https://github.com/users/jordanlambrecht/projects/3
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: feature-request, planned, not-planned
          label-operator: OR
